### ISSUE TITLE
What are the input polarizing images in dataset?

### ISSUE THREAD

**Issue by LordSlime** [Ethereal-Tian/DPS_Net#1]
Your work is really great! However, I encounter some problems while reproducing the experiment. I got a really good result using the dataset you provided while get a bad result using my own dataset. I thought it could be wrong input of network. In your paper, the input of network are 6 images, 2 RGB image and 4 polarizing images(I guess they are aolp images and dolp images?). But in your code, you only input 4 images, 2 RGB images and 2 polarizing images. The polarizing image in your dataset is like below:
![lpL_0](https://github.com/Ethereal-Tian/DPS-Net/assets/52435418/7eb261f4-f360-4c2b-bb8e-219fa9948ad0)
Is this image a combination of aolp image and dolp image? I will really appreciated it if you can solve my problem.

**Comment by Ethereal-Tian** [comment]
The images you mentioned are the combination of  AoLP image and DoLP image，you can follow the dataset file to recover the them.

**Comment by Ethereal-Tian** [comment]
The images you mentioned above are the combination of AoLP image and DoLP image，you can follow the dataset file to recover them.
